"""Shared constants for Silver layer transformations."""

DATE_FORMAT = "dd.MM.yyyy"

UNKNOWN_VALUE = "unknown"

KM_PER_MILE = 1.60934

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400

MIN_ATHLETE_AGE = 5
MAX_ATHLETE_AGE = 100
INVALID_BIRTH_YEAR = 1193

MIN_VALID_SPEED_KMH = 0
MAX_VALID_SPEED_KMH = 50
SPEED_ROUND_SCALE = 3

HASH_DELIMITER = "||"
HASH_BITS = 256